#!/bin/sh

#connect Vbuddy to WSL
~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# cleanup
rm -rf obj_dir
rm -f sigdelay.vcd

# run Verilator to translate Verilog into C++, including C++ test bench
verilator -Wall --cc --trace sigdelay.sv counter.sv ram2ports.sv --exe sigdelay_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

# run executable simulation file
obj_dir/Vsigdelay

#config vbuddy.cfg
ls /dev/ttyU* > vbuddy.cfg