#!/bin/sh

#connect Vbuddy to WSL
~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# cleanup
rm -rf obj_dir
rm -f sinegen.vcd

# run Verilator to translate Verilog into C++, including C++ test bench
verilator -Wall --cc --trace sinegen.sv counter.sv rom.sv --exe sinegen_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen

# run executable simulation file
obj_dir/Vsinegen

#config vbuddy.cfg
ls /dev/ttyU* > vbuddy.cfg